export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const ADD_USER_SUCCESSFULLY ="ADD_USER_SUCCESSFULLY"
export const GET_USER_DATA="GET_USER_DATA"
export const GET_USERS="GET_USERS"
export const GET_PROFILE_USER="GET_PROFILE_USER"